#cloud-config
package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - python-swiftclient

runcmd:
    - pip install celery
    - git clone -b elias https://github.com/ka2le/accpro.git /home/ubuntu/accpro
    - cd /home/ubuntu/accpro
    - export master_ip=
    - export C_FORCE_ROOT="true"
    - export LC_ALL=C
    - chmod +x convert.sh
    - sudo -H -u ubuntu bash -c "celery worker -l info -A tasks"