#cloud-config
package_update: true
package_upgrade: true

packages:
    - git
    - python-pip

runcmd:
    - pip install celery
    - git clone https://github.com/ka2le/accpro.git /home/ubuntu/accpro
    - export master_ip=
    - export C_FORCE_ROOT="true"
    - cd /home/ubuntu/accpro
    - celery worker -l info -A tasks --concurrency=1